services:
  node_1:
    working_dir: /app
    environment:
      - HOST=node_1
      - NODE_N=1
      - PORT=5000
      - DB_HOST=db
      - BD_USER=root
      - DB_PASSWORD=password123
      - SERVER_IP=172.16.114.128
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app

  db:
    environment:
      MARIADB_ROOT_PASSWORD: 'password123'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      MARIADB_DATABASE: 'db_tickets'
    image: mariadb
    volumes:
      - .db/:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge